name: Build and deploy Node.js app to Azure Web App - nextjs-deploy-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip artifact for deployment
        run: |
          mkdir -p build
          mv .next build/.next
          mv package.json build/package.json
          mv package-lock.json build/package-lock.json
          cd build
          zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Create wwwroot directory
        run: mkdir -p D:/home/site/wwwroot

      - name: Unzip artifact for deployment
        run: unzip release.zip -d D:/home/site/wwwroot

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Install dependencies on Azure'
        run: |
          cd D:/home/site/wwwroot
          npm install

      - name: 'Build on Azure'
        run: |
          cd D:/home/site/wwwroot
          npx next build

      - name: 'Start the application'
        run: |
          cd D:/home/site/wwwroot
          npx next start
